/**
 * The road vehicles at real dimensions: the player's sports car, four traffic models
 * (hatchback, sedan, van, box truck) and a city bus.
 */
import { roadVehicle } from './cars.ts';
import { paint } from './surfaces.ts';
import type { VehicleDraft } from './vehicle-spec.ts';

// Waiting on the engine: a per-instance colour, so one traffic model could come in many paints.
export const CAR_DRAFTS: readonly VehicleDraft[] = [
  roadVehicle({
    id: 'sports-car',
    kind: 'car',
    mass: 1400,
    paint: paint('racing-red', [0.55, 0.02, 0.01]),
    length: 4.4,
    width: 1.92,
    body: 0.72,
    clearance: 0.14,
    wheelRadius: 0.34,
    wheelbase: 2.62,
    cabin: { length: 1.9, height: 0.42, z: -0.35 },
  }),
  roadVehicle({
    id: 'hatchback',
    kind: 'car',
    mass: 1150,
    paint: paint('sky-blue', [0.12, 0.3, 0.6]),
    length: 4.0,
    width: 1.75,
    body: 0.72,
    clearance: 0.16,
    wheelRadius: 0.31,
    wheelbase: 2.5,
    cabin: { length: 2.3, height: 0.62, z: -0.5 },
  }),
  roadVehicle({
    id: 'sedan',
    kind: 'car',
    mass: 1500,
    paint: paint('graphite', [0.08, 0.085, 0.09]),
    length: 4.8,
    width: 1.85,
    body: 0.7,
    clearance: 0.15,
    wheelRadius: 0.33,
    wheelbase: 2.85,
    cabin: { length: 2.5, height: 0.6, z: -0.2 },
  }),
  roadVehicle({
    id: 'van',
    kind: 'van',
    mass: 2300,
    paint: paint('van-white', [0.78, 0.78, 0.76]),
    length: 5.3,
    width: 2.0,
    body: 1.1,
    clearance: 0.18,
    wheelRadius: 0.35,
    wheelbase: 3.3,
    cabin: { length: 4.3, height: 0.95, z: -0.3, rake: 0.6 },
  }),
  roadVehicle({
    id: 'box-truck',
    kind: 'truck',
    mass: 9000,
    paint: paint('truck-green', [0.05, 0.25, 0.1]),
    length: 8.2,
    width: 2.5,
    body: 1.2,
    clearance: 0.3,
    wheelRadius: 0.5,
    wheelbase: 3.8,
    cabin: { length: 1.7, height: 1.0, z: 3.1, rake: 0.25 },
    rearAxles: 2,
    extra: [
      {
        shape: 'rounded-box',
        size: [2.5, 2.5, 6.1],
        position: [0, 2.75, -1.0],
        surface: 'cargo',
        bevel: 0.08,
        segments: 3,
      },
    ],
  }),
  roadVehicle({
    id: 'city-bus',
    kind: 'bus',
    mass: 13000,
    paint: paint('bus-yellow', [0.75, 0.45, 0.02]),
    length: 12,
    width: 2.55,
    body: 1.0,
    clearance: 0.3,
    wheelRadius: 0.5,
    wheelbase: 6,
    cabin: { length: 11.4, height: 1.5, z: 0, rake: 0.15 },
  }),
];
